export {
  type Aggregate,
  allFollows,
  type Follow,
  type GetArticleResult,
  type GetRechercheResult,
  type GetTexteResult,
  type ListTextesResult,
} from "./aggregates.js"

export {
  allDossierLegislatifTypes,
  type ArborescenceLien,
  type ArborescenceNiveau,
  type DossierLegislatif,
  type DossierLegislatifType,
  type Echeancier,
  type EcheancierLigne,
} from "./legal/dole.js"

export {
  type Article,
  type ArticleVersion,
  bestItemForDate,
  type Contexte,
  type Etat,
  type Idcc,
  type LegalObject,
  type LegalObjectType,
  type Lien,
  type LienArt,
  type LienSectionTa,
  type MetaCommun,
  type MetaTexteChronicle,
  pathnameFromLegalId,
  pathnameFromLegalObject,
  pathnameFromLegalObjectTypeAndId,
  rootTypeFromLegalId,
  walkStructureTree,
  walkTextelrLiensArticles,
  type SectionTa,
  type Textekali,
  type Textelr,
  type TextelrVersion,
  type TextelrVersionLienTxt,
  type TexteVersion,
  type TitreTm,
  type TitreTxt,
  type Tm,
  type TmLienTxt,
  type Versions,
} from "./legal/index.js"

export {
  extractOrigineFromId,
  extractTypeFromId,
  gitPathFromId,
  idRegExp,
  idsOrigines,
  idsTypes,
  type IdOrigine,
  type IdType,
} from "./legal/ids.js"

export {
  allJoNatures,
  allJoOrigines,
  allJorfArticleEtats,
  allJorfArticleLienArticleOrigines,
  allJorfArticleNatures,
  allJorfArticleOrigines,
  allJorfArticleTexteNatures,
  allJorfCategoriesTags,
  allJorfSectionTaLienArtEtats,
  allJorfSectionTaLienArtOrigines,
  allJorfSectionTaLienSectionTaEtats,
  allJorfSectionTaTexteNatures,
  allJorfTexteNatures,
  allJorfTexteOrigines,
  allJorfTexteVersionLienNatures,
  allJorfTexteVersionLienTypes,
  allJorfTextelrEtats,
  allJorfTextelrLienArtEtats,
  allJorfTextelrLienArtNatures,
  allJorfTextelrLienArtOrigines,
  type Jo,
  type JoLienTxt,
  type JoNature,
  type JoOrigine,
  type JorfArticle,
  type JorfArticleEtat,
  type JorfArticleLienArticleOrigine,
  type JorfArticleMetaArticle,
  type JorfArticleNature,
  type JorfArticleOrigine,
  type JorfArticleTexteNature,
  type JorfArticleTm,
  type JorfArticleVersion,
  type JorfCategorieTag,
  type JorfMetaTexteChronicle,
  type JorfMetaTexteVersion,
  type JorfSectionTa,
  type JorfSectionTaLienArt,
  type JorfSectionTaLienArtEtat,
  type JorfSectionTaLienArtOrigine,
  type JorfSectionTaLienSectionTa,
  type JorfSectionTaLienSectionTaEtat,
  type JorfSectionTaStructure,
  type JorfSectionTaTexteNature,
  type JorfSectionTaTm,
  type JorfTexte,
  type JorfTexteMetaCommun,
  type JorfTexteNature,
  type JorfTexteOrigine,
  type JorfTexteVersion,
  type JorfTexteVersionLien,
  type JorfTexteVersionLienNature,
  type JorfTexteVersionLienType,
  type JorfTextelr,
  type JorfTextelrEtat,
  type JorfTextelrLienArt,
  type JorfTextelrLienArtEtat,
  type JorfTextelrLienArtNature,
  type JorfTextelrLienArtOrigine,
  type JorfTextelrLienSectionTa,
  type JorfTextelrStructure,
  type JorfTextelrVersion,
  type JorfTextelrVersions,
  type JoTm,
  walkJoTm,
} from "./legal/jorf.js"

export {
  allLegiArticleEtats,
  allLegiArticleLienArticleOrigines,
  allLegiArticleLienNatures,
  allLegiArticleLienTypes,
  allLegiArticleNatures,
  allLegiArticleOrigines,
  allLegiArticleTexteNatures,
  allLegiCategoriesTags,
  allLegiSectionTaLienArtEtats,
  allLegiSectionTaLienArtOrigines,
  allLegiSectionTaLienSectionTaEtats,
  allLegiSectionTaTexteNatures,
  allLegiTexteEtats,
  allLegiTexteNatures,
  allLegiTexteOrigines,
  allLegiTexteVersionLienNatures,
  allLegiTexteVersionLienTypes,
  allLegiTextelrLienArtEtats,
  allLegiTextelrLienArtOrigines,
  allLegiTextelrLienSectionTaEtats,
  type LegiArticle,
  type LegiArticleEtat,
  type LegiArticleLien,
  type LegiArticleLienArticleOrigine,
  type LegiArticleLienNature,
  type LegiArticleLienType,
  type LegiArticleMetaArticle,
  type LegiArticleNature,
  type LegiArticleOrigine,
  type LegiArticleTexteNature,
  type LegiArticleTm,
  type LegiArticleVersion,
  type LegiCategorieTag,
  type LegiMetaTexteChronicle,
  type LegiMetaTexteVersion,
  type LegiSectionTa,
  type LegiSectionTaLienArt,
  type LegiSectionTaLienArtEtat,
  type LegiSectionTaLienArtOrigine,
  type LegiSectionTaLienSectionTa,
  type LegiSectionTaLienSectionTaEtat,
  type LegiSectionTaStructure,
  type LegiSectionTaTexteNature,
  type LegiSectionTaTm,
  type LegiTexte,
  type LegiTexteEtat,
  type LegiTexteNature,
  type LegiTexteOrigine,
  type LegiTexteVersion,
  type LegiTexteVersionLien,
  type LegiTexteVersionLienNature,
  type LegiTexteVersionLienType,
  type LegiTextelr,
  type LegiTextelrLienArt,
  type LegiTextelrLienArtEtat,
  type LegiTextelrLienArtOrigine,
  type LegiTextelrLienSectionTa,
  type LegiTextelrLienSectionTaEtat,
  type LegiTextelrStructure,
  type LegiTextelrVersion,
  type LegiTextelrVersions,
} from "./legal/legi.js"

export { type LegalObjectReferences } from "./legal/references.js"

export {
  allArticleTypes,
  allSens,
  type ArticleGitDb,
  type ArticleLienDb,
  type ArticleType,
  type SectionTaGitDb,
  type Sens,
  type TexteVersionGitDb,
  type TexteVersionLienDb,
} from "./legal/shared.js"

export { parseDossierLegislatif } from "./parsers/dole.js"

export { xmlParser } from "./parsers/shared.js"
