name: Test

on:
  push:
  workflow_dispatch:

enable-email-notifications: true

jobs:
  test:
    runs-on: juridique
    steps:
      - name: Checkout tricoteuses-juridique
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Setup Tricoteuses Tisseuse
        uses: ./.forgejo/actions/setup_tisseuse
        with:
          ASSEMBLEE_DB_PASSWORD: "${{ secrets.ASSEMBLEE_DB_PASSWORD }}"
          LEGI_ANOMALIES_DB_PASSWORD: "${{ secrets.LEGI_ANOMALIES_DB_PASSWORD }}"
          LEGI_DB_PASSWORD: "${{ secrets.LEGI_DB_PASSWORD }}"
          TISSEUSE_DB_PASSWORD: "${{ secrets.TISSEUSE_DB_PASSWORD }}"
      - name: Extract titles from texts
        run: npx tsx src/scripts/extract_texts_titles_infos.ts
        working-directory: packages/tisseuse/
      - name: Launch Tisseuse tests
        run: npm test
        working-directory: packages/tisseuse/
      - name: Launch Chercheuse tests
        run: npm test
        working-directory: packages/chercheuse/
      - name: Extract texts infos (without generating anything)
        run: npx tsx src/scripts/extract_texts_infos.ts
        working-directory: packages/tisseuse/

  update_tisseuse_database:
    needs: [test]
    if: forge.ref_name == 'main'
    runs-on: juridique
    uses: ./.forgejo/workflows/update_tisseuse_database.yml
    secrets:
      ASSEMBLEE_DB_PASSWORD: "${{ secrets.ASSEMBLEE_DB_PASSWORD }}"
      LEGI_ANOMALIES_DB_PASSWORD: "${{ secrets.LEGI_ANOMALIES_DB_PASSWORD }}"
      LEGI_DB_PASSWORD: "${{ secrets.LEGI_DB_PASSWORD }}"
      TISSEUSE_DB_PASSWORD: "${{ secrets.TISSEUSE_DB_PASSWORD }}"
