on:
  push:
  workflow_dispatch:

enable-email-notifications: true

jobs:
  test:
    runs-on: juridique
    steps:
      - name: Checkout tricoteuses-juridique
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Install tricoteuses-juridique
        run: npm install
      - name: Configure tisseuse
        run: |
          cat > .env << EOF
          # PostgreSQL database configuration
          ASSEMBLEE_DB_NAME="assemblee"
          ASSEMBLEE_DB_HOST="${{ vars.ASSEMBLEE_DB_HOST }}"
          ASSEMBLEE_DB_PORT=${{ vars.ASSEMBLEE_DB_PORT }}
          ASSEMBLEE_DB_USER="assemblee"
          ASSEMBLEE_DB_PASSWORD="${{ secrets.ASSEMBLEE_DB_PASSWORD }}"

          # PostgreSQL database configuration
          LEGI_DB_NAME="legi"
          LEGI_DB_HOST="${{ vars.LEGI_DB_HOST }}"
          LEGI_DB_PORT=${{ vars.LEGI_DB_PORT }}
          LEGI_DB_USER="legi"
          LEGI_DB_PASSWORD="${{ secrets.LEGI_DB_PASSWORD }}"
          EOF
        working-directory: packages/tisseuse/
      - name: Extract titles from texts
        run: npx tsx src/scripts/extract_texts_titles_infos.ts
        working-directory: packages/tisseuse/
      - name: Launch every tricoteuses-juridique tests (tisseuse…)
        run: npm test
