on:
  workflow_call:
  workflow_dispatch:

enable-email-notifications: true

jobs:
  update_tisseuse_database:
    if: forge.ref_name == 'main'
    runs-on: juridique
    steps:
      - name: Checkout tricoteuses-juridique
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Setup Tricoteuses Tisseuse
        uses: ./.forgejo/actions/setup_tisseuse
        with:
          ASSEMBLEE_DB_PASSWORD: "${{ secrets.ASSEMBLEE_DB_PASSWORD }}"
          LEGI_ANOMALIES_DB_PASSWORD: "${{ secrets.LEGI_ANOMALIES_DB_PASSWORD }}"
          LEGI_DB_PASSWORD: "${{ secrets.LEGI_DB_PASSWORD }}"
          TISSEUSE_DB_PASSWORD: "${{ secrets.TISSEUSE_DB_PASSWORD }}"
      - name: Configure Tisseuse database
        run: npm run configure
        working-directory: packages/tisseuse/
      - name: Extract titles from texts
        run: npx tsx src/scripts/extract_texts_titles_infos.ts
        working-directory: packages/tisseuse/
      - name: Extract texts infos
        run: npx tsx src/scripts/extract_texts_infos.ts --autocompletion
        working-directory: packages/tisseuse/
