name: Setup Tricoteuses Tisseuse
description: Install Tricoteuses Tisseuse & create its environment
inputs:
  ASSEMBLEE_DB_PASSWORD_RO:
    description: "Password of Assemblée PostgreSQL read-only database"
    required: true
  EUROPE_DB_PASSWORD_RO:
    description: "Password of Europe PostgreSQL read-only database"
    required: true
  LEGI_DB_PASSWORD_RO:
    description: "Password of Légifrance PostgreSQL read-only database"
    required: true
  TISSEUSE_DB_PASSWORD_RO:
    description: "Password of Tisseuse PostgreSQL database"
    required: true
runs:
  using: composite
  steps:
    - name: Install Tricoteuses Exploratrice
      run: npm install
      shell: bash
      working-directory: packages/exploratrice/
    - name: Set Tricoteuses Exploratrice environment
      run: |
        cat > .env << EOF
        # Assemblée PostgreSQL database configuration
        ASSEMBLEE_DB_NAME="canutes_assemblee"
        ASSEMBLEE_DB_HOST="${{ vars.DB_HOST_RO }}"
        ASSEMBLEE_DB_PORT=${{ vars.DB_PORT }}
        ASSEMBLEE_DB_USER="assemblee_ro"
        ASSEMBLEE_DB_PASSWORD="${{ inputs.ASSEMBLEE_DB_PASSWORD_RO }}"

        # Path of repository containing repository of Assemblée documents
        # in various formats (HTML, PDF, etc)
        ASSEMBLEE_DOCUMENTS_DIR="../../../assemblee-data/Documents/"

        # Europe PostgreSQL database configuration
        EUROPE_DB_NAME="canutes_europe"
        EUROPE_DB_HOST="${{ vars.DB_HOST_RO }}"
        EUROPE_DB_PORT=${{ vars.DB_PORT }}
        EUROPE_DB_USER="europe_ro"
        EUROPE_DB_PASSWORD="${{ inputs.CANUTES_DB_PASSWORD_RO }}"

        # Légifrance PostgreSQL database configuration
        LEGI_DB_NAME="canutes_legifrance"
        LEGI_DB_HOST="${{ vars.DB_HOST_RO }}"
        LEGI_DB_PORT=${{ vars.DB_PORT }}
        LEGI_DB_USER="legifrance_ro"
        LEGI_DB_PASSWORD="${{ inputs.LEGI_DB_PASSWORD_RO }}"

        # Tisseuse PostgreSQL database configuration
        TISSEUSE_DB_NAME="canutes_tisseuse"
        TISSEUSE_DB_HOST="${{ vars.DB_HOST_RO }}"
        TISSEUSE_DB_PORT=${{ vars.DB_PORT }}
        TISSEUSE_DB_USER="tisseuse_ro"
        TISSEUSE_DB_PASSWORD="${{ inputs.TISSEUSE_DB_PASSWORD_RO }}"

        TITLE="Tricoteuses (action)"
        EOF
      shell: bash
      working-directory: packages/exploratrice/
