name: Setup Tricoteuses Tisseuse
description: Install Tricoteuses Tisseuse & create its environment
inputs:
  assemblee_db_password:
    description: "Password of Assemblée PostgreSQL database"
    required: true
  legi_anomalies_db_password:
    description: "Password of Légifrance Anomalies PostgreSQL database"
    required: true
  legi_db_password:
    description: "Password of Légifrance PostgreSQL database"
    required: true
  tisseuse_db_password:
    description: "Password of Tisseuse PostgreSQL database"
    required: true
runs:
  using: composite
  steps:
    - name: Install tricoteuses-juridique
      run: npm install
      shell: bash
    - name: Set Tricoteuses Tisseuse environment
      run: |
        cat > .env << EOF
        # Assemblée PostgreSQL database configuration
        ASSEMBLEE_DB_NAME="assemblee"
        ASSEMBLEE_DB_HOST="${{ vars.ASSEMBLEE_DB_HOST }}"
        ASSEMBLEE_DB_PORT=${{ vars.ASSEMBLEE_DB_PORT }}
        ASSEMBLEE_DB_USER="assemblee"
        ASSEMBLEE_DB_PASSWORD="${{ inputs.assemblee_db_password }}"

        # Légifrance Anomalies PostgreSQL database configuration
        LEGI_ANOMALIES_DB_NAME="legi_anomalies"
        LEGI_ANOMALIES_DB_HOST="${{ vars.LEGI_ANOMALIES_DB_HOST }}"
        LEGI_ANOMALIES_DB_PORT=${{ vars.LEGI_ANOMALIES_DB_PORT }}
        LEGI_ANOMALIES_DB_USER="legi_anomalies"
        LEGI_ANOMALIES_DB_PASSWORD="${{ inputs.legi_anomalies_db_password }}"

        # Légifrance PostgreSQL database configuration
        LEGI_DB_NAME="legi"
        LEGI_DB_HOST="${{ vars.LEGI_DB_HOST }}"
        LEGI_DB_PORT=${{ vars.LEGI_DB_PORT }}
        LEGI_DB_USER="legi"
        LEGI_DB_PASSWORD="${{ inputs.legi_db_password }}"

        # Tisseuse PostgreSQL database configuration
        TISSEUSE_DB_NAME="tisseuse"
        TISSEUSE_DB_HOST="${{ vars.TISSEUSE_DB_HOST }}"
        TISSEUSE_DB_PORT=${{ vars.TISSEUSE_DB_PORT }}
        TISSEUSE_DB_USER="tisseuse"
        TISSEUSE_DB_PASSWORD="${{ inputs.tisseuse_db_password }}"
        EOF
      shell: bash
      working-directory: packages/tisseuse/
