name: Setup Tricoteuses Tisseuse
description: Install Tricoteuses Tisseuse & create its environment
inputs:
  ASSEMBLEE_DB_PASSWORD_RW:
    description: "Password of Assemblée PostgreSQL read-write database"
    required: true
  EUROPE_DB_PASSWORD_RW:
    description: "Password of Europe PostgreSQL read-write database"
    required: true
  LEGI_ANOMALIES_DB_PASSWORD_RW:
    description: "Password of Légifrance Anomalies PostgreSQL read-write database"
    required: true
  LEGI_DB_PASSWORD_RW:
    description: "Password of Légifrance PostgreSQL read-write database"
    required: true
  TISSEUSE_DB_PASSWORD_RW:
    description: "Password of Tisseuse PostgreSQL read-write database"
    required: true
runs:
  using: composite
  steps:
    - name: Install Tricoteuses Tisseuse
      run: npm install
      shell: bash
      working-directory: packages/tisseuse/
    - name: Set Tricoteuses Tisseuse environment
      run: |
        cat > .env << EOF
        # Assemblée PostgreSQL database configuration
        ASSEMBLEE_DB_NAME="canutes_assemblee"
        ASSEMBLEE_DB_HOST="${{ vars.DB_HOST_RW }}"
        ASSEMBLEE_DB_PORT=${{ vars.DB_PORT }}
        ASSEMBLEE_DB_USER="assemblee_rw"
        ASSEMBLEE_DB_PASSWORD="${{ inputs.ASSEMBLEE_DB_PASSWORD_RW }}"

        # Europe PostgreSQL database configuration
        EUROPE_DB_NAME="canutes_europe"
        EUROPE_DB_HOST="${{ vars.DB_HOST_RW }}"
        EUROPE_DB_PORT=${{ vars.DB_PORT }}
        EUROPE_DB_USER="europe_rw"
        EUROPE_DB_PASSWORD="${{ inputs.CANUTES_DB_PASSWORD_RW }}"

        # Légifrance Anomalies PostgreSQL database configuration
        LEGI_ANOMALIES_DB_NAME="canutes_anomalies"
        LEGI_ANOMALIES_DB_HOST="${{ vars.DB_HOST_RW }}"
        LEGI_ANOMALIES_DB_PORT=${{ vars.DB_PORT }}
        LEGI_ANOMALIES_DB_USER="anomalies_rw"
        LEGI_ANOMALIES_DB_PASSWORD="${{ inputs.LEGI_ANOMALIES_DB_PASSWORD_RW }}"

        # Légifrance PostgreSQL database configuration
        LEGI_DB_NAME="canutes_legifrance"
        LEGI_DB_HOST="${{ vars.DB_HOST_RW }}"
        LEGI_DB_PORT=${{ vars.DB_PORT }}
        LEGI_DB_USER="legifrance_rw"
        LEGI_DB_PASSWORD="${{ inputs.LEGI_DB_PASSWORD_RW }}"

        LINK_BASE_URL="https://tricoteuses.fr/"
        LINK_TYPE="Exploratrice"

        # Tisseuse PostgreSQL database configuration
        TISSEUSE_DB_NAME="canutes_tisseuse"
        TISSEUSE_DB_HOST="${{ vars.DB_HOST_RW }}"
        TISSEUSE_DB_PORT=${{ vars.DB_PORT }}
        TISSEUSE_DB_USER="tisseuse_rw"
        TISSEUSE_DB_PASSWORD="${{ inputs.TISSEUSE_DB_PASSWORD_RW }}"
        EOF
      shell: bash
      working-directory: packages/tisseuse/
