import { XMLParser } from "fast-xml-parser"
import he from "he"

export const xmlParser = new XMLParser({
  attributeNamePrefix: "@",
  ignoreAttributes: false,
  stopNodes: [
    "ARTICLE.BLOC_TEXTUEL.CONTENU",
    "ARTICLE.NOTA.CONTENU",
    "ARTICLE.SM.CONTENU",
    "DOSSIER_LEGISLATIF.CONTENU.CONTENU_DOSSIER_1",
    "DOSSIER_LEGISLATIF.CONTENU.CONTENU_DOSSIER_2",
    "DOSSIER_LEGISLATIF.CONTENU.CONTENU_DOSSIER_3",
    "DOSSIER_LEGISLATIF.CONTENU.CONTENU_DOSSIER_4",
    "DOSSIER_LEGISLATIF.CONTENU.CONTENU_DOSSIER_5",
    "DOSSIER_LEGISLATIF.CONTENU.EXPOSE_MOTIF",
    "TEXTE_VERSION.ABRO.CONTENU",
    "TEXTE_VERSION.NOTA.CONTENU",
    "TEXTE_VERSION.NOTICE.CONTENU",
    "TEXTE_VERSION.RECT.CONTENU",
    "TEXTE_VERSION.SIGNATAIRES.CONTENU",
    "TEXTE_VERSION.SM.CONTENU",
    "TEXTE_VERSION.TP.CONTENU",
    "TEXTE_VERSION.VISAS.CONTENU",
  ],
  tagValueProcessor: (_tagName, tagValue) => he.decode(tagValue),
})
